source 'https://rubygems.org'
ruby File.read(Dir.getwd + "/.ruby-version").strip.split("-").first
gem 'dotenv-rails', :groups => [:development, :test] # needs to be at top

gem 'rails', '~> 4.1.0'
gem 'pg'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'rails-i18n', '~> 4.0.0' # import standard translations
gem 'jbuilder', '~> 1.2'

gem 'unicorn-rails'

group :test, :development do
  gem 'guard-rspec', require: false
  gem 'pry-debugger'
  gem 'i18n-tasks', '~> 0.2.10' # Gem for testing i18n
  gem 'spring'
  gem 'rubocop', require: false
end

group :test do
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'shoulda-callback-matchers', '>=0.3.0'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'capybara', '~> 2.1'
  gem 'database_cleaner'
end

group :development do
  gem 'rails-erd'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :production do
  gem 'rails_12factor'
end
